# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.8
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
        types:
            - python
    -   id: end-of-file-fixer
        types:
          - python
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        types:
            - python
        args: [--line-length=120]
-   repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        types:
            - python
        args: ['--max-line-length=120', '--extend-ignore=E203']
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint
        types:
            - python
        # '--disable=duplicate-code' stands for almost the same preprocessing scripts for different datasets, but makes
        # sense to avoid putting them together or exposing as functions
        args: ['--disable=C0330, C0326, E0401', '--max-line-length=120']
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
    -   id: mypy
        types:
            - python
        args: ['--disallow-untyped-calls', '--disallow-untyped-defs', '--disallow-incomplete-defs',
               '--disallow-untyped-decorators', '--no-implicit-optional', '--warn-redundant-casts',
               '--ignore-missing-imports']
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
        types:
            - python
        args: ['-t=B101,B102,B103,B104,B105,B106,B107,B108,B110,B112,B201,B301,B302,B303,B304,B305,B306,B307,B308,B309,B310,B311,B312,B313,B314,B315,B316,B317,B318,B319,B320,B321,B323,B324,B325,B401,B402,B403,B404,B405,B406,B407,B408,B409,B410,B411,B412,B413,B501,B502,B503,B504,B505,B506,B507,B601,B602,B603,B604,B605,B606,B607,B608,B609,B610,B611,B701,B702,B703']
