version: "3.8"
services:
  metron_conduit:
    build:
      context: .
      dockerfile: ./metron_conduit/Dockerfile
    image: metron/metron_conduit:latest
    container_name: metron_conduit
    expose:
      - ${METRON_CORE_STREAM_PORT}
      - ${METRON_SHINE_STREAM_PORT}
    command: python metron_conduit_run.py
      video_streamer.mshine_streamer_worker.address=${METRON_SHINE_HOSTNAME}
      video_streamer.mcore_streamer_worker.address=${METRON_CORE_HOSTNAME}
      video_streamer.mshine_streamer_worker.port=${METRON_SHINE_STREAM_PORT}
      video_streamer.mcore_streamer_worker.port=${METRON_CORE_STREAM_PORT}
      ${METRON_CONDUIT_CMD_CONFIG_ARGS}